### ISSUE TITLE
Phrases

### ISSUE THREAD

**Issue by uxes** [Vict0rC/guacamole-client-cz#1]
Ahoj, 
prohlížel jsem si překlady a zarazil jsem se na pár věcech které bych navrhnul ponechat v originálním znění (podobně jak není přeloženo slovo anonym do napřiklad 'neznamy uzivatel')

Schránka (Clipboard)
Strojopis (TypeScript)
Přístupová fráze (PassPhrase)

**Comment by Vict0rC** [comment]
To je dobra poznamka... Jsem pro... Co na to @odolezal ?

**Comment by Vict0rC** [comment]
fixed
